package com.douyin.mixcut.dto;

import lombok.Data;

import java.util.Locale;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * 混剪参数 —— 直接对应老板那段话的每一句。
 *
 * "时长大概在1分钟到2分20秒，控制在50秒到150秒之间"      → minSec / maxSec（硬约束，默认 50/150）
 * "中间更密集的时候可以100秒附近"                        → dense=true 时向 100s 收敛
 * "15秒的我在前3秒，下一条我用后面3秒"                     → sliceSec=3 + variantSeed 位移
 * "把15秒拆成5个3秒扑到视频里"                            → explodeLongClips=true
 * "AI开头吸引的钩子"                                     → aiHook / hookText / hookSec
 * "中间各种实拍的和明星的音频加视频的分解"                  → bodyRatio / celebrityRatio
 * "再加我们自己的产品的"                                  → productSlots
 * "这个画面然后配下面的音频混剪"                           → voice + bgm 分轨混音
 */
@Data
public class MixParams {

    // ---- 时长 ----
    /** 下限（秒），默认 50 */
    private Integer minSec = 50;
    /** 上限（秒），默认 150 */
    private Integer maxSec = 150;
    /** 密集模式：向 100 秒附近收敛 */
    private Boolean dense = true;
    /** 直接指定目标时长；为空则在区间内自动取 */
    private Integer targetSec;
    /** 新版参数名，优先级高于 targetSec；保留旧字段兼容已有项目。 */
    private Integer targetDurationSec;

    // ---- 拆条 ----
    /** 单片时长，默认 3 秒 */
    private Double sliceSec = 3.0;
    /** equal=均等拆分，random=在上下限内随机分配。 */
    private String durationAllocationMode = "random";
    /** 单片随机分配的最短/最长秒数。 */
    private Double minSegmentSec = 1.5;
    private Double maxSegmentSec = 5.0;
    /** 单片时长抖动（±秒），避免每片一模一样的机械感 */
    private Double sliceJitter = 0.4;
    /** 长素材是否拆成多个 slice（15s → 5×3s） */
    private Boolean explodeLongClips = true;
    /** 同素材在一条成片里最多用几片 */
    private Integer maxSlicesPerMaterial = 5;

    // ---- 去重 ----
    /** 去重严格度：off=不校验 / standard=禁止完全重复 / strict=额外禁止同源时间重叠。 */
    private String dedupStrictness = "standard";
    /** 允许同一素材源被拆成多段互不重叠的画面（默认允许）；关闭时严格模式会尽量压低同源复用。 */
    private Boolean allowSameSourceNonoverlap = true;

    // ---- 结构配比 ----
    /** 营销结构序列：1 钩子、2 讲解/痛点、3 产品展示/证明、4 成交收口。 */
    private String marketingStructure = "123234";
    /** 钩子时长（秒） */
    private Double hookSec = 3.0;
    /** 明星/达人素材占比 0~1 */
    private Double celebrityRatio = 0.25;
    /** 产品段插入次数（均匀分布在时间线上） */
    private Integer productSlots = 3;
    /** 每个产品段时长（秒） */
    private Double productSec = 3.0;
    /** 是否加片尾引导 */
    private Boolean endcard = true;
    /** 片尾收尾视觉时长；留空时与单片时长一致，避免破坏已有项目。 */
    private Double endcardSec;
    /** 仅在明确要求独立片尾卡时阻断；默认使用产品图/主体镜头等安全回退。 */
    private Boolean requireDedicatedEndcard = false;

    // ---- 画面规格 ----
    private Integer width = 1080;
    private Integer height = 1920;
    private Double fps = 30.0;

    // ---- 音频 ----
    /** BGM 音量 0~1，默认 0.22（有人声时压低） */
    private Double bgmVolume = 0.22;
    /** 指定 BGM 素材 id；为空则从 bgm 角色里随机 */
    private Long bgmMaterialId;
    /** 本次任务开始前由服务端从近期版本快照填充的音频使用计数，用户输入不会控制此字段。 */
    private java.util.Map<String, Integer> recentAudioUsage = new java.util.LinkedHashMap<>();
    /** 指定人声素材 id；为空则从 voice 角色里随机 */
    private Long voiceMaterialId;
    /** 钩子片段专用音频；只在钩子画面时间窗内播放。 */
    private Long hookAudioMaterialId;
    /** 出片前若素材不足是否自动从公开源补齐（true=自动补齐，false=仅用现有素材，人为干预）。 */
    private Boolean autoUseCrawledMaterials = false;
    /** local=仅本地；builtin=内置公开来源；extended=公开直链/用户官方授权来源。 */
    private String materialSourceMode = "local";
    /** 自动按已选人声回退匹配钩子音频。 */
    private Boolean autoMatchAudio = true;
    /** 钩子音频相对音量 0~1。 */
    private Double hookAudioVolume = 1.0;
    /** material-audio=使用独立口播/BGM，original=保留原片声音，ai-voice=AI 口播替代原片人声。 */
    private String audioMode = "material-audio";
    /** 原片声音保留时的相对音量。 */
    private Double originalAudioVolume = 0.28;
    /** AI 配音使用的已允许音色。 */
    private String ttsVoice = "zh-CN-XiaoxiaoNeural";
    /** 是否根据现有 ASR 时间轴生成全片字幕。仅烧录用户明确授权转录的素材字幕。 */
    private Boolean autoSubtitles = false;
    /** 是否把 AI 配音的真实 ASR 字幕烧录进画面（时间轴来自实际生成音频，不做脚本时长猜测）。 */
    private Boolean burnAiVoiceCaptions = true;
    /** 是否在拼接阶段清理素材自带的旧字幕安全区，避免旧字幕和新字幕叠加。 */
    private Boolean cleanSourceSubtitles = false;
    /** subtitle-safe-band=遮盖常见底部旧字幕区；off=不处理。 */
    private String sourceSubtitleCleanMode = "off";

    // ---- 钩子文案 ----
    /** 是否用 AI 生成钩子文案 */
    private Boolean aiHook = true;
    /** 手填钩子文案（填了就不调 AI） */
    private String hookText;
    /** 当前任务内部标记：该钩子是否由 AI 自动生成；修复版本仅可替换这类钩子。 */
    private Boolean autoGeneratedHook = false;
    /** 是否把钩子文案烧进画面 */
    private Boolean burnHookText = true;
    private Integer hookFontSize = 64;
    private String hookFontColor = "white";

    // ---- 钩子策略与中段再钩子 ----
    /** 钩子策略：conflict/result/suspense/reward/counterintuitive/question/visual-impact；空则由项目语义 + variant 轮换推导。 */
    private String hookStrategy;
    /** 是否自动生成并安排中段再钩子（mid-roll rehook）。 */
    private Boolean autoRehook = false;
    /** 中段再钩子文案；留空且开启 autoRehook 时按策略自动生成。 */
    private String rehookText;
    /** 是否把中段再钩子文案烧进画面。 */
    private Boolean burnRehookText = true;
    /** 可选字体文件路径；留空时由渲染器按当前服务器操作系统选择 */
    private String fontFile;

    // ---- 素材范围 ----
    /** 只用这些素材（为空 = 用素材库全部） */
    private List<Long> materialIds;
    /** 只用这些目录下的素材 */
    private List<Long> folderIds;
    /** 八段式或通用顺序读取：每一步只使用自己的应用内文件夹和备用文件夹。 */
    private List<FolderReadStep> folderReadSteps = new ArrayList<>();
    /** 启用后严格按 folderReadSteps 的序号生成时间线，禁止跨步骤和空目录回退。 */
    private Boolean strictFolderSequence = false;
    /** rules-only=仅人工分组；cross-folder=允许在所选文件夹间同角色随机。 */
    private String materialSelectionMode = "rules-only";
    /** 默认只使用与当前项目文本和素材标签匹配的画面素材。 */
    private Boolean projectRelevantOnly = true;
    /** 任务调度元数据；保留在参数 JSON 中，避免连续模式解析时丢失用户设置。 */
    private Boolean continuous = false;
    /** 是否启用自定义片头。 */
    private Boolean introEnabled = false;
    /** fixed=固定选择一条；rotate=在本次授权素材池中按批次轮换。 */
    private String introMode = "fixed";
    /** 固定模式的首选片头；轮换模式会优先将它排在首轮。 */
    private Long introMaterialId;
    private Double introDurationSec = 3.0;
    /** 轮换模式下要求本批次各条首个片头使用不同素材。 */
    private Boolean introNoRepeat = true;
    /** 候选不足时仅在用户显式允许后才轮换后重复。 */
    private Boolean introAllowRepeatWhenInsufficient = false;

    // ---- 严格交付 ----
    /**
     * AI 自动出片 / 严格交付流水线显式开启后，hook / duplicate / subtitleSync 等提示性质检
     * 升级为硬性拦截（fail）；默认关闭，保持与既有人工/半自动交付完全兼容（warn 不拦截）。
     * 当前端选择自主生产模式（autonomyMode=autonomous）且本字段未显式填写时，normalized()
     * 会默认开启；人工/半自动（assist/auto）与旧版客户端不带该字段时仍保持默认关闭。
     */
    private Boolean strictDelivery = false;
    /** Distinguishes an omitted JSON field from an explicit false choice. */
    private transient boolean strictDeliveryExplicit;

    public Boolean getStrictDelivery() {
        return strictDelivery == null ? Boolean.FALSE : strictDelivery;
    }

    public void setStrictDelivery(Boolean strictDelivery) {
        this.strictDelivery = strictDelivery;
        this.strictDeliveryExplicit = strictDelivery != null;
    }

    // ---- AI 生产模式 ----
    /**
     * AI 自主生产模式，由前端在选择时冻结并写入提交参数：
     * assist=辅助（人工确认每一项）/ auto=半自动（AI 建议、批量执行）/ autonomous=自主生产（全流程自动）。
     * 该字段只描述本次任务的授权边界，不驱动任何新的外部能力；normalized() 仅收敛非法值，
     * 不会改变用户的选择。旧版客户端不带该字段时收敛为 assist（最保守）。
     */
    private String autonomyMode = "assist";

    // ---- 批量差异化 ----
    /** 随机种子；同 seed 出同样的片，便于复现 */
    private Long seed;
    /** 输出文件名前缀 */
    private String namePrefix = "mix";

    /** 一项人工定义的应用内文件夹读取步骤；不携带或暴露物理路径。 */
    @Data
    public static class FolderReadStep {
        private Integer order;
        private String name;
        private Long folderId;
        private Long fallbackFolderId;
        private Boolean enabled = true;
        private Boolean required = true;
        private Double targetSec;
        private Boolean aiSelect = true;
        private Integer maxSlicesPerMaterial;
        /** block=素材不足即停止；fallback=仅使用本步骤配置的备用文件夹。 */
        private String shortagePolicy = "block";
        /** 提交时写入的展示快照，运行时不以它访问文件系统。 */
        private String folderNameSnapshot;
        private String fallbackFolderNameSnapshot;
    }

    /** 把非法值纠正回安全范围，避免前端乱填直接把 ffmpeg 打挂 */
    public MixParams normalized() {
        if (minSec == null || minSec < 5) minSec = 50;
        if (maxSec == null || maxSec < minSec) maxSec = Math.max(minSec + 10, 150);
        if (maxSec > 300) maxSec = 300;
        if (targetDurationSec != null) targetSec = targetDurationSec;
        if (sliceSec == null || sliceSec < 0.8) sliceSec = 3.0;
        if (sliceSec > 15) sliceSec = 15.0;
        if (!"equal".equalsIgnoreCase(durationAllocationMode)
                && !"random".equalsIgnoreCase(durationAllocationMode)) durationAllocationMode = "random";
        if (minSegmentSec == null || minSegmentSec < 0.8) minSegmentSec = 1.5;
        if (maxSegmentSec == null || maxSegmentSec < minSegmentSec) maxSegmentSec = Math.max(minSegmentSec, 5.0);
        if (maxSegmentSec > 15) maxSegmentSec = 15.0;
        if (sliceJitter == null || sliceJitter < 0) sliceJitter = 0.0;
        if (maxSlicesPerMaterial == null || maxSlicesPerMaterial < 1) maxSlicesPerMaterial = 3;
        if (dedupStrictness == null || dedupStrictness.isBlank()) dedupStrictness = "standard";
        if (!"off".equalsIgnoreCase(dedupStrictness)
                && !"standard".equalsIgnoreCase(dedupStrictness)
                && !"strict".equalsIgnoreCase(dedupStrictness)) dedupStrictness = "standard";
        if (allowSameSourceNonoverlap == null) allowSameSourceNonoverlap = true;
        try {
            marketingStructure = com.douyin.mixcut.service.MarketingStructurePlanner.normalizePattern(marketingStructure);
        } catch (IllegalArgumentException e) {
            marketingStructure = "123234";
        }
        if (hookSec == null || hookSec < 0) hookSec = 3.0;
        if (celebrityRatio == null || celebrityRatio < 0) celebrityRatio = 0.0;
        if (celebrityRatio > 0.8) celebrityRatio = 0.8;
        if (productSlots == null || productSlots < 0) productSlots = 0;
        if (productSlots > 10) productSlots = 10;
        if (productSec == null || productSec < 0.8) productSec = 3.0;
        if (endcardSec == null) endcardSec = sliceSec;
        if (endcardSec < 0.8) endcardSec = 0.8;
        if (endcardSec > 15) endcardSec = 15.0;
        if (requireDedicatedEndcard == null) requireDedicatedEndcard = false;
        if (width == null || width < 240) width = 1080;
        if (height == null || height < 240) height = 1920;
        if (fps == null || fps < 12 || fps > 60) fps = 30.0;
        if (bgmVolume == null || bgmVolume < 0) bgmVolume = 0.22;
        if (bgmVolume > 1) bgmVolume = 1.0;
        if (hookAudioVolume == null || hookAudioVolume < 0) hookAudioVolume = 1.0;
        if (hookAudioVolume > 1) hookAudioVolume = 1.0;
        if (!"material-audio".equalsIgnoreCase(audioMode) && !"original".equalsIgnoreCase(audioMode)
                && !"ai-voice".equalsIgnoreCase(audioMode) && !"silent".equalsIgnoreCase(audioMode)) audioMode = "material-audio";
        // A user-selected narration material is an explicit instruction, never a fallback hint.
        if (voiceMaterialId != null) audioMode = "material-audio";
        if (originalAudioVolume == null || originalAudioVolume < 0) originalAudioVolume = 0.28;
        if (originalAudioVolume > 1) originalAudioVolume = 1.0;
        if (ttsVoice == null || ttsVoice.isBlank()) ttsVoice = "zh-CN-XiaoxiaoNeural";
        if (autoSubtitles == null) autoSubtitles = false;
        if (burnAiVoiceCaptions == null) burnAiVoiceCaptions = true;
        if (cleanSourceSubtitles == null) cleanSourceSubtitles = false;
        if (sourceSubtitleCleanMode == null || sourceSubtitleCleanMode.isBlank()) sourceSubtitleCleanMode = "off";
        if (!"off".equalsIgnoreCase(sourceSubtitleCleanMode)
                && !"subtitle-safe-band".equalsIgnoreCase(sourceSubtitleCleanMode)) sourceSubtitleCleanMode = "off";
        if (Boolean.FALSE.equals(cleanSourceSubtitles)) sourceSubtitleCleanMode = "off";
        if (autoMatchAudio == null) autoMatchAudio = true;
        if (recentAudioUsage == null) recentAudioUsage = new java.util.LinkedHashMap<>();
        if (!"local".equalsIgnoreCase(materialSourceMode) && !"builtin".equalsIgnoreCase(materialSourceMode)
                && !"extended".equalsIgnoreCase(materialSourceMode)) materialSourceMode = "local";
        autoUseCrawledMaterials = !"local".equalsIgnoreCase(materialSourceMode);
        if (hookFontSize == null || hookFontSize < 12) hookFontSize = 64;
        if (hookFontColor == null || hookFontColor.isBlank()) hookFontColor = "white";
        namePrefix = safeOutputPrefix(namePrefix);
        if (dense == null) dense = true;
        if (explodeLongClips == null) explodeLongClips = true;
        if (endcard == null) endcard = true;
        if (aiHook == null) aiHook = true;
        if (autoGeneratedHook == null) autoGeneratedHook = false;
        if (burnHookText == null) burnHookText = true;
        if (autoRehook == null) autoRehook = false;
        if (burnRehookText == null) burnRehookText = true;
        if (hookStrategy != null) hookStrategy = hookStrategy.trim();
        if (rehookText != null) rehookText = rehookText.trim();
        if (introEnabled == null) introEnabled = false;
        if (!"fixed".equalsIgnoreCase(introMode) && !"rotate".equalsIgnoreCase(introMode)) introMode = "fixed";
        if (introNoRepeat == null) introNoRepeat = true;
        if (introAllowRepeatWhenInsufficient == null) introAllowRepeatWhenInsufficient = false;
        if (introDurationSec == null || introDurationSec < 0.8) introDurationSec = 3.0;
        if (introDurationSec > 15) introDurationSec = 15.0;
        if (!"rules-only".equalsIgnoreCase(materialSelectionMode)
                && !"cross-folder".equalsIgnoreCase(materialSelectionMode)) materialSelectionMode = "rules-only";
        if (strictFolderSequence == null) strictFolderSequence = false;
        if (autonomyMode == null || autonomyMode.isBlank()) autonomyMode = "assist";
        if (!"assist".equals(autonomyMode) && !"auto".equals(autonomyMode) && !"autonomous".equals(autonomyMode)) {
            autonomyMode = "assist";
        }
        // 自主生产模式默认开启严格交付；显式填写过的值（true/false）优先，旧版/其他模式保持默认关闭。
        if (!strictDeliveryExplicit && "autonomous".equals(autonomyMode)) strictDelivery = true;
        if (strictDelivery == null) strictDelivery = false;
        normalizeFolderReadSteps();
        if (projectRelevantOnly == null) projectRelevantOnly = true;
        if (targetSec != null) {
            if (targetSec < minSec) targetSec = minSec;
            if (targetSec > maxSec) targetSec = maxSec;
        }
        return this;
    }

    private void normalizeFolderReadSteps() {
        if (folderReadSteps == null) {
            folderReadSteps = new ArrayList<>();
            return;
        }
        if (folderReadSteps.size() > 32) folderReadSteps = new ArrayList<>(folderReadSteps.subList(0, 32));
        List<FolderReadStep> normalized = new ArrayList<>();
        Set<Integer> seenOrders = new HashSet<>();
        int nextOrder = 1;
        for (FolderReadStep step : folderReadSteps) {
            if (step == null || Boolean.FALSE.equals(step.getEnabled())) continue;
            int order = step.getOrder() == null ? nextOrder : step.getOrder();
            if (order < 1 || order > 32 || !seenOrders.add(order)) continue;
            nextOrder = Math.max(nextOrder, order + 1);
            step.setOrder(order);
            if (step.getName() == null || step.getName().isBlank()) step.setName("读取步骤 " + order);
            else step.setName(step.getName().trim().substring(0, Math.min(80, step.getName().trim().length())));
            if (step.getFolderId() != null && step.getFolderId() <= 0) step.setFolderId(null);
            if (step.getFallbackFolderId() != null && step.getFallbackFolderId() <= 0) step.setFallbackFolderId(null);
            if (step.getTargetSec() != null) step.setTargetSec(Math.max(0.8, Math.min(300, step.getTargetSec())));
            if (step.getMaxSlicesPerMaterial() != null) step.setMaxSlicesPerMaterial(Math.max(1, Math.min(20, step.getMaxSlicesPerMaterial())));
            if (step.getRequired() == null) step.setRequired(true);
            if (step.getAiSelect() == null) step.setAiSelect(true);
            if (!"block".equalsIgnoreCase(step.getShortagePolicy()) && !"fallback".equalsIgnoreCase(step.getShortagePolicy())) {
                step.setShortagePolicy("block");
            }
            normalized.add(step);
        }
        normalized.sort(java.util.Comparator.comparing(FolderReadStep::getOrder));
        folderReadSteps = normalized;
    }

    private static String safeOutputPrefix(String value) {
        String cleaned = value == null ? "mix" : value.replaceAll("[\\\\/:*?\"<>|\\x00-\\x1F]+", "_");
        cleaned = cleaned.replaceAll("[. ]+$", "").trim();
        if (cleaned.isBlank()) cleaned = "mix";
        if (cleaned.matches("(?i)^(con|prn|aux|nul|com[1-9]|lpt[1-9])$")) cleaned = "_" + cleaned;
        return cleaned.length() <= 80 ? cleaned : cleaned.substring(0, 80);
    }
}
