<template>
  <div class="resource-page">
    <div class="card"><div class="card-title">资源中心 <span class="hint">按类型查找创作所需的模板、提示词和参考资料</span><span style="flex:1"></span><el-tag size="small" :type="usingFallback ? 'warning' : 'success'" effect="plain">{{ usingFallback ? '本地目录' : '在线目录' }}</el-tag><el-button size="small" :loading="loading" @click="loadCatalog">刷新目录</el-button></div>
      <el-form inline class="filter-form"><el-form-item label="关键词"><el-input v-model="keyword" clearable placeholder="搜索名称、标签或描述" style="width:250px" @keyup.enter="loadCatalog" /></el-form-item><el-form-item label="类型"><el-select v-model="category" style="width:150px"><el-option label="全部" value="all" /><el-option v-for="item in categories" :key="item" :label="item" :value="item" /></el-select></el-form-item></el-form>
    </div>
    <el-alert v-if="errorMessage" type="warning" show-icon :closable="false" :title="errorMessage" style="margin-bottom:12px" />
    <div v-loading="loading" class="resource-grid"><div v-for="item in filteredItems" :key="item.id" class="resource-item"><div class="resource-icon" :class="`icon-${item.category}`">{{ iconFor(item.category) }}</div><div class="resource-body"><div class="resource-title">{{ item.name }}</div><div class="muted resource-meta">{{ item.category }} · {{ item.updatedAt || '内置资源' }}</div><div class="resource-description">{{ item.description }}</div><div class="resource-tags"><el-tag v-for="tag in item.tags" :key="tag" size="small" effect="plain">{{ tag }}</el-tag><el-tag v-if="item.url" size="small" type="success" effect="plain">官方入口</el-tag><el-tag v-if="item.accountRequired" size="small" type="warning" effect="plain">需账号</el-tag><el-tag v-else size="small" type="info" effect="plain">免登录查看</el-tag><el-tag v-if="item.billingAvailable" size="small" type="warning" effect="plain">可能计费</el-tag></div></div><el-button class="resource-action" size="small" type="primary" plain @click="useResource(item)">{{ item.category === '提示词' ? '复制提示词' : item.url ? '打开官方入口' : '查看资源' }}</el-button></div></div>
    <el-empty v-if="!loading && !filteredItems.length" description="没有匹配的资源" />
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api'
const fallbackCatalog = [{ id: 'prompt-hook', name: '前三秒强钩子', category: '提示词', description: '快速生成带有冲突、结果或反常识开场的短视频钩子。', tags: ['钩子', '短视频'] }, { id: 'prompt-product', name: '产品卖点提炼', category: '提示词', description: '把产品材料转成可验证、可口播、适合字幕呈现的卖点。', tags: ['卖点', '口播'] }, { id: 'template-review', name: '真实测评结构', category: '模板', description: '适合成分、食品和日用品的测评类脚本结构。', tags: ['测评', '脚本'] }, { id: 'template-live', name: '直播切片节奏', category: '模板', description: '将直播高信息密度片段整理为适合投放的节奏顺序。', tags: ['直播', '混剪'] }, { id: 'guide-compliance', name: '广告合规检查清单', category: '参考资料', description: '发布前检查夸大、绝对化、医疗功效等常见表述风险。', tags: ['合规', '发布前'] }, { id: 'guide-subtitle', name: '字幕可读性规范', category: '参考资料', description: '帮助统一字幕长度、断句、节奏与画面安全区。', tags: ['字幕', '规范'] }]
const items = ref([]); const loading = ref(false); const usingFallback = ref(true); const errorMessage = ref(''); const keyword = ref(''); const category = ref('all')
const categories = computed(() => [...new Set(items.value.map((item) => item.category).filter(Boolean))]); const filteredItems = computed(() => { const query = keyword.value.trim().toLowerCase(); return items.value.filter((item) => (category.value === 'all' || item.category === category.value) && (!query || [item.name, item.description, ...(item.tags || [])].join(' ').toLowerCase().includes(query))) })
function normalizeCatalog (result) { const data = result?.data ?? result; const list = Array.isArray(data) ? data : (data?.items || data?.resources || data?.list || []); return list.map((item, index) => ({ id: item.id || item.key || `resource-${index}`, name: item.name || item.title || '未命名资源', category: item.category || item.type || '其他', description: item.description || item.summary || '暂无描述', tags: Array.isArray(item.tags) ? item.tags : (item.tags ? String(item.tags).split(',') : []), url: item.url || item.officialUrl || '', accountRequired: Boolean(item.accountRequired), billingAvailable: Boolean(item.billingAvailable), updatedAt: item.updatedAt || item.updated_at || '' })) }
async function loadCatalog () { loading.value = true; errorMessage.value = ''; try { if (typeof api.resourceCatalog !== 'function') throw new Error('resourceCatalog unavailable'); const result = await api.resourceCatalog(); const remote = normalizeCatalog(result); if (!remote.length) throw new Error('empty catalog'); items.value = remote; usingFallback.value = false } catch { items.value = fallbackCatalog; usingFallback.value = true; errorMessage.value = '在线资源目录暂不可用，当前展示本地内置目录。' } finally { loading.value = false } }
function iconFor (category) { return category === '提示词' ? 'P' : category === '模板' ? 'T' : category === '参考资料' ? 'R' : 'O' }
async function useResource (item) { if (item.category === '提示词' && navigator.clipboard?.writeText) { await navigator.clipboard.writeText(item.description); ElMessage.success('提示词内容已复制'); return } if (item.url?.startsWith('#')) { window.location.hash = item.url.slice(1); return } if (item.url) { window.open(item.url, '_blank', 'noopener,noreferrer'); return } ElMessage.info(`${item.name}：${item.description}`) }
onMounted(loadCatalog)
</script>

<style scoped>
.filter-form { margin-bottom: -10px; }.resource-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(330px, 1fr)); gap: 12px; }.resource-item { position: relative; display: flex; gap: 12px; min-height: 166px; padding: 16px; background: #fff; border: 1px solid #ebeef5; border-radius: 6px; box-shadow: 0 2px 8px rgba(31,45,61,.05); }.resource-icon { flex: 0 0 40px; width: 40px; height: 40px; line-height: 40px; border-radius: 5px; text-align: center; color: #fff; font-size: 20px; font-weight: 700; background: #409eff; }.icon-模板 { background: #67c23a; }.icon-参考资料 { background: #e6a23c; }.resource-body { min-width: 0; padding-bottom: 30px; }.resource-title { font-weight: 600; color: #303133; }.resource-meta { margin-top: 4px; font-size: 12px; }.resource-description { margin-top: 10px; color: #606266; font-size: 13px; line-height: 1.5; }.resource-tags { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 10px; }.resource-action { position: absolute; left: 68px; bottom: 12px; }@media (max-width:600px) { .resource-grid { grid-template-columns: 1fr; }.filter-form .el-form-item { margin-right: 8px; } }
</style>
