param(
  [Parameter(Mandatory = $true)][string]$Root,
  [Parameter(Mandatory = $true)][string]$OutputPath
)
$ErrorActionPreference = 'Stop'
$rootPath = (Resolve-Path -LiteralPath $Root).Path
$notesPath = Join-Path $rootPath 'backend\src\main\resources\release-notes.json'
$appPropsPath = Join-Path $rootPath 'backend\src\main\java\com\douyin\mixcut\config\AppProps.java'
$notesVersion = [string](Get-Content -Raw -LiteralPath $notesPath -Encoding UTF8 | ConvertFrom-Json).version
$appPropsText = Get-Content -Raw -LiteralPath $appPropsPath -Encoding UTF8
$match = [regex]::Match($appPropsText, 'RELEASE_VERSION\s*=\s*"([^"]+)"')
if (-not $match.Success) { throw 'AppProps.java is missing RELEASE_VERSION' }
$appVersion = $match.Groups[1].Value
if ($notesVersion -ne $appVersion) { throw "Version mismatch: release-notes=$notesVersion AppProps=$appVersion" }
$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $parent | Out-Null
$lines = @(
  '; Generated by build_installer.bat. Do not edit manually.'
  ('#define AppVersion "{0}"' -f $notesVersion)
)
$lines | Set-Content -LiteralPath $OutputPath -Encoding ASCII
Write-Host ('Installer version unified: ' + $notesVersion)
